Some common terms to remember:

  1. Corpus
  2. Vocubulary
  3. Document
  4. Word
  

# Bag of words

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({"text":["The cat slept peacefully",
                          "Stars twinkled brightly",
                          "She smiled warmly",
                          "Rain fell softly"],"output":[1,1,0,0]})
df

text  output
0  The cat slept peacefully       1
1   Stars twinkled brightly       1
2         She smiled warmly       0
3          Rain fell softly       0

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [4]:
bow = cv.fit_transform(df['text'])

In [5]:
#vocabulary
print(cv.vocabulary_)

{'the': 10, 'cat': 1, 'slept': 6, 'peacefully': 3, 'stars': 9, 'twinkled': 11, 'brightly': 0, 'she': 5, 'smiled': 7, 'warmly': 12, 'rain': 4, 'fell': 2, 'softly': 8}


In [6]:
bow.toarray()

array([[0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0]])

In [7]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[0 1 0 1 0 0 1 0 0 0 1 0 0]]
[[1 0 0 0 0 0 0 0 0 1 0 1 0]]
[[0 0 0 0 0 1 0 1 0 0 0 0 1]]
[[0 0 1 0 1 0 0 0 1 0 0 0 0]]


In [8]:
#new
cv.transform(['Bappy watch dswithbappy']).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [9]:
X = bow.toarray()
y = df['output']

# N-grams

In [10]:
df = pd.DataFrame({"text":["The cat slept peacefully",
                          "Stars twinkled brightly",
                          "She smiled warmly",
                          "Rain fell softly"],"output":[1,1,0,0]})
df

text  output
0  The cat slept peacefully       1
1   Stars twinkled brightly       1
2         She smiled warmly       0
3          Rain fell softly       0

In [11]:
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [12]:
bow = cv.fit_transform(df['text'])

In [13]:
print(cv.vocabulary_)

{'the cat': 7, 'cat slept': 0, 'slept peacefully': 4, 'stars twinkled': 6, 'twinkled brightly': 8, 'she smiled': 3, 'smiled warmly': 5, 'rain fell': 2, 'fell softly': 1}


In [14]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[1 0 0 0 1 0 0 1 0]]
[[0 0 0 0 0 0 1 0 1]]
[[0 0 0 1 0 1 0 0 0]]
[[0 1 1 0 0 0 0 0 0]]


In [15]:
#TI gram
#BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [16]:
bow = cv.fit_transform(df['text'])

In [17]:
print(cv.vocabulary_)

{'the cat slept': 4, 'cat slept peacefully': 0, 'stars twinkled brightly': 3, 'she smiled warmly': 2, 'rain fell softly': 1}


In [18]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[1 0 0 0 1]]
[[0 0 0 1 0]]
[[0 0 1 0 0]]
[[0 1 0 0 0]]


# TF-IDF(Term frequency-Inverse document frequency)

In [19]:
df = pd.DataFrame({"text":["The cat slept peacefully",
                          "Stars twinkled brightly",
                          "She smiled warmly",
                          "Rain fell softly"],"output":[1,1,0,0]})
df

text  output
0  The cat slept peacefully       1
1   Stars twinkled brightly       1
2         She smiled warmly       0
3          Rain fell softly       0

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid = TfidfVectorizer()

In [21]:
arr = tfid.fit_transform(df['text']).toarray()

In [22]:
arr

array([[0.        , 0.5       , 0.        , 0.5       , 0.        ,
        0.        , 0.5       , 0.        , 0.        , 0.        ,
        0.5       , 0.        , 0.        ],
       [0.57735027, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.57735027,
        0.        , 0.57735027, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.57735027, 0.        , 0.57735027, 0.        , 0.        ,
        0.        , 0.        , 0.57735027],
       [0.        , 0.        , 0.57735027, 0.        , 0.57735027,
        0.        , 0.        , 0.        , 0.57735027, 0.        ,
        0.        , 0.        , 0.        ]])

In [23]:
print(tfid.idf_)

[1.91629073 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073
 1.91629073]
